# Generated by Django 5.2.6 on 2025-09-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('none', 'Nenhum'), ('ronaldo', 'Bomba do Ronaldo'), ('nene', 'Bomba do Seu Nenê'), ('eber', 'Bomba do Eber/Abel')], default='none', max_length=20)),
            ],
        ),
    ]
